### ISSUE TITLE
itstool-2.0.4: problem with gnumeric-1.12.35

### ISSUE THREAD

**Issue by 0-wiz-0** [itstool/itstool#22]
With older itstool versions, gnumeric-1.12.35 built fine.
With 2.0.4, it breaks as follows:
````
  GEN    cs/
Warning: Could not merge de translation for msgid:
b'Permission is granted to copy, distribute and/or modify this document under the terms of the GNU Free Documentation License (GFDL), Version 1.1 or any later version published by the Free Software Foundation with no Invariant Sections, no Front-Cover Texts, and no Back-Cover Texts. You can find a copy of the GFDL at this <ulink type="help" url="ghelp:fdl">link</ulink> or in the file COPYING-DOCS distributed with this manual.'
Warning: Could not merge cs translation for msgid:
b'The chapters of this version of the <application>Gnumeric</application> manual are organized as follows: <_:itemizedlist-1/>'
Warning: Could not merge cs translation for msgid:
b'Both the <guimenu>Edit</guimenu> menu and the context menu have an extra menu entry called <guimenuitem>Paste Special...</guimenuitem> which can be used during a cut and paste operation to selectively transfer some of the original cell contents or to alter the contents in specific ways. This option allows the transfer of only the cell contents, only the cell formats or only the calculated values of the cells. The transferred contents can also be mathematically combined with the current contents of cells in the new location. Alternatively, the selection can be transposed. See <xref linkend="sect-movecopy-pastespecial"/> for more information on the <guimenuitem>Paste Special...</guimenuitem> command.'
Warning: Could not merge cs translation for msgid:
b'An existing spreadsheet file can be opened in several ways. If the file has an icon on the desktop, this icon can be clicked or double-clicked with the mouse button. Similarly, if a file manager, such as the <application>Nautilus</application> file manager, lists the file, then the file name can be clicked and opened. If <application>Gnumeric</application> is already opened, a file can be opened by clicking on the <guimenu>File</guimenu> and selecting the <guimenuitem>Open</guimenuitem> menu item. Alternatively, the "Open file" button on the toolbar, <inlinemediaobject> <imageobject> <imagedata fileref="figures/button-open.png" format="PNG"/> </imageobject> <textobject> <phrase>An image of the "Open File" button.</phrase> </textobject> </inlinemediaobject>, can be used or the <keycap>F3</keycap> key clicked. All three of these open the <interface>Open File</interface> dialog. You can then select the spreadsheet file you wish to open. <application>Gnumeric</application> can open many different types of spreadsheet file formats.'
Warning: Could not merge cs translation for msgid:
b'To finish the function, close the parenthesis. The cell should now show =sum(B1:C2). Press enter and the formula is entered.'
Warning: Could not merge cs translation for msgid:
b'This tab allows you to choose the border for the selected cells. You can select one of many border styles (none, single line, double line,...) and colors. You can also have different borders on different sides of the cell. <_:figure-1/> To choose a border for a cell or a selection, select border style and color in the right side of the tab and click on the buttons corresponding to the sides of the cells in the left side of the tab. In addition to the buttons for left, right, top, and bottom sides, you also have buttons for drawing diagonal and reverse diagonal of the cell. (Strictly speaking, these cannot be called borders, but it is natural to put them in this tab.) The lowest row of buttons contains buttons <guibutton>None</guibutton> and <guibutton>Outline</guibutton>. Clicking on <guibutton>None</guibutton> removes all borders from the cell; clicking on <guibutton>Outline</guibutton> puts border on all sides of the cell or selection.'
Warning: Could not merge cs translation for msgid:
b"Using <inlineequation> <_:alt-1/> <_:mathphrase-2/> </inlineequation> as the z-value of the <inlineequation> <_:alt-3/> <_:mathphrase-4/> </inlineequation> percentile of the standard normal distribution, set the initial estimate of the number of iterations required as the smallest integer <inlineequation> <_:alt-5/> <_:mathphrase-6/> </inlineequation> such that <_:equation-7/>. Note that if <inlineequation> <_:alt-8/> <_:mathphrase-9/> </inlineequation> is small, it would be more appropriate to use the student's t-distribution of <inlineequation> <_:alt-10/> <_:mathphrase-11/> </inlineequation> instead of <inlineequation> <_:alt-12/> <_:mathphrase-13/> </inlineequation>."
[1]   Segmentation fault (core dumped) (cd "cs/" && its...
````
and leaves a core file. The python backtrace looks like this:
````
Program terminated with signal SIGSEGV, Segmentation fault.
#0  _PyEval_EvalCodeWithName (_co=0x75bd28ffd8f0, globals=<optimized out>, locals=<optimized out>, args=0x75bd206355f0, argcount=2, kwnames=0x0, kwargs=kwargs@entry=0x0,
    kwcount=kwcount@entry=0, kwstep=kwstep@entry=2, defs=defs@entry=0x0, defcount=defcount@entry=0, kwdefs=kwdefs@entry=0x0, closure=closure@entry=0x0, name=name@entry=0x0,
    qualname=qualname@entry=0x0) at Python/ceval.c:3947
3947    Python/ceval.c: No such file or directory.
(gdb) bt
#0  _PyEval_EvalCodeWithName (_co=0x75bd28ffd8f0, globals=<optimized out>, locals=<optimized out>, args=0x75bd206355f0, argcount=2, kwnames=0x0, kwargs=kwargs@entry=0x0, 
    kwcount=kwcount@entry=0, kwstep=kwstep@entry=2, defs=defs@entry=0x0, defcount=defcount@entry=0, kwdefs=kwdefs@entry=0x0, closure=closure@entry=0x0, name=name@entry=0x0, 
    qualname=qualname@entry=0x0) at Python/ceval.c:3947
#1  0x000075bd299340b6 in PyEval_EvalCodeEx (_co=<optimized out>, globals=<optimized out>, locals=locals@entry=0x0, args=args@entry=0x75bd206355f0, argcount=<optimized out>, 
    kws=kws@entry=0x0, kwcount=kwcount@entry=0, defs=defs@entry=0x0, defcount=defcount@entry=0, kwdefs=0x0, closure=0x0) at Python/ceval.c:4174
#2  0x000075bd29897095 in function_call (func=0x75bd282e2828, arg=0x75bd206355d8, kw=0x0) at Objects/funcobject.c:604
#3  0x000075bd29867219 in PyObject_Call (func=0x75bd282e2828, args=<optimized out>, kwargs=<optimized out>) at Objects/abstract.c:2261
#4  0x000075bd299347a8 in PyEval_CallObjectWithKeywords (func=<optimized out>, args=<optimized out>, kwargs=<optimized out>) at Python/ceval.c:4744
#5  0x000075bd25a425d7 in libxml_xmlErrorFuncHandler (ctx=<optimized out>, msg=<optimized out>) at libxml.c:1644
#6  0x000075bd2563a99c in xmlParserPrintFileContextInternal (input=input@entry=0x75bd20139080, channel=channel@entry=0x75bd25a42475 <libxml_xmlErrorFuncHandler>, data=data@entry=0x0)
    at error.c:208
#7  0x000075bd2563ac93 in xmlReportError (err=err@entry=0x75bd20107a58, ctxt=ctxt@entry=0x75bd20107800, 
    str=str@entry=0x75bd273e2400 "Opening and ending tag mismatch: guilabel line 416 and para\n", channel=0x75bd25a42475 <libxml_xmlErrorFuncHandler>, channel@entry=0x0, 
    data=data@entry=0x0) at error.c:406
#8  0x000075bd2563c5a8 in __xmlRaiseError (schannel=schannel@entry=0x0, channel=0x75bd2563b339 <xmlParserError>, channel@entry=0x0, data=0x75bd20107800, data@entry=0x0, 
    ctx=ctx@entry=0x75bd20107800, nod=nod@entry=0x0, domain=domain@entry=1, code=code@entry=76, level=level@entry=XML_ERR_FATAL, file=<optimized out>, file@entry=0x0, line=416, 
    line@entry=0, str1=0x75bd2013355f "guilabel", str2=0x75bd201643b4 "para", str3=str3@entry=0x0, int1=int1@entry=416, col=490, col@entry=0, 
    msg=msg@entry=0x75bd25730b40 "Opening and ending tag mismatch: %s line %d and %s\n") at error.c:633
#9  0x000075bd25641276 in xmlFatalErrMsgStrIntStr (ctxt=ctxt@entry=0x75bd20107800, error=error@entry=XML_ERR_TAG_NAME_MISMATCH, 
    msg=msg@entry=0x75bd25730b40 "Opening and ending tag mismatch: %s line %d and %s\n", str1=<optimized out>, val=val@entry=416, str2=<optimized out>) at parser.c:717
#10 0x000075bd2564f707 in xmlParseEndTag2 (ctxt=ctxt@entry=0x75bd20107800, prefix=0x0, URI=0x0, line=line@entry=416, nsNr=0, tlen=<optimized out>) at parser.c:9672
#11 0x000075bd25654558 in xmlParseElement (ctxt=ctxt@entry=0x75bd20107800) at parser.c:10040
#12 0x000075bd25653bd2 in xmlParseContent (ctxt=ctxt@entry=0x75bd20107800) at parser.c:9849
#13 0x000075bd256544fe in xmlParseElement (ctxt=ctxt@entry=0x75bd20107800) at parser.c:10017
#14 0x000075bd25653bd2 in xmlParseContent (ctxt=ctxt@entry=0x75bd20107800) at parser.c:9849
#15 0x000075bd256544fe in xmlParseElement (ctxt=ctxt@entry=0x75bd20107800) at parser.c:10017
#16 0x000075bd256582bf in xmlParseDocument (ctxt=0x75bd20107800) at parser.c:10714
#17 0x000075bd25a31a38 in libxml_xmlParseDocument (self=<optimized out>, args=<optimized out>) at libxml2-py.c:4958
#18 0x000075bd298b869b in _PyCFunction_FastCallDict (func_obj=func_obj@entry=0x75bd27704cf8, args=0x75bd29779e28, nargs=<optimized out>, kwargs=kwargs@entry=0x0)
    at Objects/methodobject.c:234
#19 0x000075bd298b89ef in _PyCFunction_FastCallKeywords (func=func@entry=0x75bd27704cf8, stack=<optimized out>, nargs=nargs@entry=1, kwnames=kwnames@entry=0x0)
    at Objects/methodobject.c:294
#20 0x000075bd29933f62 in call_function (pp_stack=pp_stack@entry=0x7f7ffff9dc88, oparg=<optimized out>, kwnames=kwnames@entry=0x0) at Python/ceval.c:4824
#21 0x000075bd29938eb3 in _PyEval_EvalFrameDefault (f=<optimized out>, throwflag=<optimized out>) at Python/ceval.c:3322
#22 0x000075bd29933020 in _PyFunction_FastCall (co=<optimized out>, args=<optimized out>, nargs=1, globals=<optimized out>) at Python/ceval.c:4906
#23 0x000075bd29933cfb in fast_function (func=<optimized out>, stack=<optimized out>, nargs=<optimized out>, kwnames=<optimized out>) at Python/ceval.c:4948
#24 0x000075bd29933e6d in call_function (pp_stack=pp_stack@entry=0x7f7ffff9de78, oparg=<optimized out>, kwnames=kwnames@entry=0x0) at Python/ceval.c:4845
#25 0x000075bd29938eb3 in _PyEval_EvalFrameDefault (f=<optimized out>, throwflag=<optimized out>) at Python/ceval.c:3322
#26 0x000075bd29933a0e in _PyEval_EvalCodeWithName (_co=0x75bd28ffe8b0, globals=<optimized out>, locals=locals@entry=0x0, args=args@entry=0x75bd206a4218, argcount=3,
    kwnames=0x75bd281021b0, kwargs=kwargs@entry=0x75bd206a4230, kwcount=2, kwstep=kwstep@entry=1, defs=0x75bd281106b0, defcount=2, kwdefs=kwdefs@entry=0x0,
    closure=closure@entry=0x0, name=0x75bd281f9700, qualname=qualname@entry=0x75bd2810e250) at Python/ceval.c:4153
#27 0x000075bd29933beb in fast_function (func=<optimized out>, stack=0x75bd206a4218, nargs=<optimized out>, kwnames=<optimized out>) at Python/ceval.c:4965
#28 0x000075bd29933e6d in call_function (pp_stack=pp_stack@entry=0x7f7ffff9e1c0, oparg=<optimized out>, kwnames=kwnames@entry=0x75bd28102198) at Python/ceval.c:4845
#29 0x000075bd29938b18 in _PyEval_EvalFrameDefault (f=<optimized out>, throwflag=<optimized out>) at Python/ceval.c:3338
#30 0x000075bd29933a0e in _PyEval_EvalCodeWithName (_co=0x75bd28ffe4c0, globals=<optimized out>, locals=locals@entry=0x0, args=args@entry=0x75bd20aa1620, argcount=3,
    kwnames=0x75bd28ffa9f0, kwargs=kwargs@entry=0x75bd20aa1638, kwcount=2, kwstep=kwstep@entry=1, defs=0x75bd28103ff0, defcount=2, kwdefs=kwdefs@entry=0x0,
    closure=closure@entry=0x0, name=0x75bd293634c0, qualname=qualname@entry=0x75bd2810e110) at Python/ceval.c:4153
#31 0x000075bd29933beb in fast_function (func=<optimized out>, stack=0x75bd20aa1620, nargs=<optimized out>, kwnames=<optimized out>) at Python/ceval.c:4965
#32 0x000075bd29933e6d in call_function (pp_stack=pp_stack@entry=0x7f7ffff9e500, oparg=<optimized out>, kwnames=kwnames@entry=0x75bd28ffa9d8) at Python/ceval.c:4845
#33 0x000075bd29938b18 in _PyEval_EvalFrameDefault (f=<optimized out>, throwflag=<optimized out>) at Python/ceval.c:3338
#34 0x000075bd29933a0e in _PyEval_EvalCodeWithName (_co=0x75bd28ffe4c0, globals=<optimized out>, locals=locals@entry=0x0, args=args@entry=0x75bd204d6a20, argcount=3,
---Type <return> to continue, or q <return> to quit---
    kwnames=0x75bd28ffa9f0, kwargs=kwargs@entry=0x75bd204d6a38, kwcount=2, kwstep=kwstep@entry=1, defs=0x75bd28103ff0, defcount=2, kwdefs=kwdefs@entry=0x0,
    closure=closure@entry=0x0, name=0x75bd293634c0, qualname=qualname@entry=0x75bd2810e110) at Python/ceval.c:4153
#35 0x000075bd29933beb in fast_function (func=<optimized out>, stack=0x75bd204d6a20, nargs=<optimized out>, kwnames=<optimized out>) at Python/ceval.c:4965
#36 0x000075bd29933e6d in call_function (pp_stack=pp_stack@entry=0x7f7ffff9e840, oparg=<optimized out>, kwnames=kwnames@entry=0x75bd28ffa9d8) at Python/ceval.c:4845
#37 0x000075bd29938b18 in _PyEval_EvalFrameDefault (f=<optimized out>, throwflag=<optimized out>) at Python/ceval.c:3338
#38 0x000075bd29933a0e in _PyEval_EvalCodeWithName (_co=0x75bd28ffe4c0, globals=<optimized out>, locals=locals@entry=0x0, args=args@entry=0x75bd20590a20, argcount=3,
    kwnames=0x75bd28ffa9f0, kwargs=kwargs@entry=0x75bd20590a38, kwcount=2, kwstep=kwstep@entry=1, defs=0x75bd28103ff0, defcount=2, kwdefs=kwdefs@entry=0x0,
    closure=closure@entry=0x0, name=0x75bd293634c0, qualname=qualname@entry=0x75bd2810e110) at Python/ceval.c:4153
#39 0x000075bd29933beb in fast_function (func=<optimized out>, stack=0x75bd20590a20, nargs=<optimized out>, kwnames=<optimized out>) at Python/ceval.c:4965
#40 0x000075bd29933e6d in call_function (pp_stack=pp_stack@entry=0x7f7ffff9eb80, oparg=<optimized out>, kwnames=kwnames@entry=0x75bd28ffa9d8) at Python/ceval.c:4845
#41 0x000075bd29938b18 in _PyEval_EvalFrameDefault (f=<optimized out>, throwflag=<optimized out>) at Python/ceval.c:3338
#42 0x000075bd29933a0e in _PyEval_EvalCodeWithName (_co=0x75bd28ffe4c0, globals=<optimized out>, locals=locals@entry=0x0, args=args@entry=0x75bd209e5a20, argcount=3,
    kwnames=0x75bd28ffa9f0, kwargs=kwargs@entry=0x75bd209e5a38, kwcount=2, kwstep=kwstep@entry=1, defs=0x75bd28103ff0, defcount=2, kwdefs=kwdefs@entry=0x0,
    closure=closure@entry=0x0, name=0x75bd293634c0, qualname=qualname@entry=0x75bd2810e110) at Python/ceval.c:4153
#43 0x000075bd29933beb in fast_function (func=<optimized out>, stack=0x75bd209e5a20, nargs=<optimized out>, kwnames=<optimized out>) at Python/ceval.c:4965
#44 0x000075bd29933e6d in call_function (pp_stack=pp_stack@entry=0x7f7ffff9eec0, oparg=<optimized out>, kwnames=kwnames@entry=0x75bd28ffa9d8) at Python/ceval.c:4845
#45 0x000075bd29938b18 in _PyEval_EvalFrameDefault (f=<optimized out>, throwflag=<optimized out>) at Python/ceval.c:3338
#46 0x000075bd29933a0e in _PyEval_EvalCodeWithName (_co=0x75bd28ffe4c0, globals=<optimized out>, locals=locals@entry=0x0, args=args@entry=0x75bd23c94e20, argcount=3,
    kwnames=0x75bd28ffa9f0, kwargs=kwargs@entry=0x75bd23c94e38, kwcount=2, kwstep=kwstep@entry=1, defs=0x75bd28103ff0, defcount=2, kwdefs=kwdefs@entry=0x0,
    closure=closure@entry=0x0, name=0x75bd293634c0, qualname=qualname@entry=0x75bd2810e110) at Python/ceval.c:4153
#47 0x000075bd29933beb in fast_function (func=<optimized out>, stack=0x75bd23c94e20, nargs=<optimized out>, kwnames=<optimized out>) at Python/ceval.c:4965
#48 0x000075bd29933e6d in call_function (pp_stack=pp_stack@entry=0x7f7ffff9f200, oparg=<optimized out>, kwnames=kwnames@entry=0x75bd28ffa9d8) at Python/ceval.c:4845
#49 0x000075bd29938b18 in _PyEval_EvalFrameDefault (f=<optimized out>, throwflag=<optimized out>) at Python/ceval.c:3338
#50 0x000075bd29933a0e in _PyEval_EvalCodeWithName (_co=0x75bd28ffe4c0, globals=<optimized out>, locals=locals@entry=0x0, args=args@entry=0x75bd28105198, argcount=3,
    kwnames=0x75bd281118b0, kwargs=kwargs@entry=0x75bd281051b0, kwcount=1, kwstep=kwstep@entry=1, defs=0x75bd28103ff0, defcount=2, kwdefs=kwdefs@entry=0x0,
    closure=closure@entry=0x0, name=0x75bd293634c0, qualname=qualname@entry=0x75bd2810e110) at Python/ceval.c:4153
#51 0x000075bd29933beb in fast_function (func=<optimized out>, stack=0x75bd28105198, nargs=<optimized out>, kwnames=<optimized out>) at Python/ceval.c:4965
#52 0x000075bd29933e6d in call_function (pp_stack=pp_stack@entry=0x7f7ffff9f540, oparg=<optimized out>, kwnames=kwnames@entry=0x75bd28111898) at Python/ceval.c:4845
#53 0x000075bd29938b18 in _PyEval_EvalFrameDefault (f=<optimized out>, throwflag=<optimized out>) at Python/ceval.c:3338
#54 0x000075bd29933a0e in _PyEval_EvalCodeWithName (_co=0x75bd28115660, globals=<optimized out>, locals=<optimized out>, args=<optimized out>, argcount=argcount@entry=0,
    kwnames=0x0, kwargs=kwargs@entry=0x0, kwcount=kwcount@entry=0, kwstep=kwstep@entry=2, defs=defs@entry=0x0, defcount=defcount@entry=0, kwdefs=kwdefs@entry=0x0,
    closure=closure@entry=0x0, name=name@entry=0x0, qualname=qualname@entry=0x0) at Python/ceval.c:4153
#55 0x000075bd299340b6 in PyEval_EvalCodeEx (_co=_co@entry=0x75bd28115660, globals=globals@entry=0x75bd29357e88, locals=locals@entry=0x75bd29357e88, args=args@entry=0x0,
    argcount=argcount@entry=0, kws=kws@entry=0x0, kwcount=kwcount@entry=0, defs=defs@entry=0x0, defcount=defcount@entry=0, kwdefs=kwdefs@entry=0x0, closure=closure@entry=0x0)
    at Python/ceval.c:4174
#56 0x000075bd2993412b in PyEval_EvalCode (co=co@entry=0x75bd28115660, globals=globals@entry=0x75bd29357e88, locals=locals@entry=0x75bd29357e88) at Python/ceval.c:730
#57 0x000075bd299604a1 in run_mod (mod=mod@entry=0x75bd28037ff0, filename=filename@entry=0x75bd29362070, globals=globals@entry=0x75bd29357e88, locals=locals@entry=0x75bd29357e88,
    flags=flags@entry=0x7f7ffff9f924, arena=arena@entry=0x75bd2937a8a0) at Python/pythonrun.c:980
#58 0x000075bd29962a3d in PyRun_FileExFlags (fp=fp@entry=0x75bd28778460, filename_str=filename_str@entry=0x75bd28faada0 "/usr/pkg/bin/itstool", start=start@entry=257,
    globals=globals@entry=0x75bd29357e88, locals=locals@entry=0x75bd29357e88, closeit=closeit@entry=1, flags=flags@entry=0x7f7ffff9f924) at Python/pythonrun.c:933
#59 0x000075bd29962bb6 in PyRun_SimpleFileExFlags (fp=fp@entry=0x75bd28778460, filename=<optimized out>, closeit=closeit@entry=1, flags=flags@entry=0x7f7ffff9f924)
    at Python/pythonrun.c:396
#60 0x000075bd29963006 in PyRun_AnyFileExFlags (fp=fp@entry=0x75bd28778460, filename=<optimized out>, closeit=closeit@entry=1, flags=flags@entry=0x7f7ffff9f924)
    at Python/pythonrun.c:80
#61 0x000075bd2997b0f0 in run_file (p_cf=0x7f7ffff9f924, filename=0x75bd297040e0 L"/usr/pkg/bin/itstool", fp=0x75bd28778460) at Modules/main.c:338
#62 Py_Main (argc=argc@entry=6, argv=argv@entry=0x75bd29701080) at Modules/main.c:809
#63 0x0000000000400ddd in main (argc=6, argv=0x7f7ffff9fa08) at ./Programs/python.c:69
````

This is with python-3.6.3 and libxml2 version 2.9.7.

**Comment by 0-wiz-0** [comment]
The patch for https://github.com/itstool/itstool/issues/17 does not fix this issue for me.

**Comment by ilovezfs** [comment]
@shaunix any idea what the problem here might be? This is reproducible.

**Comment by ilovezfs** [comment]
I've also reported that gnumeric cannot build with itstool 2.0.4 to gnumeric here: https://bugzilla.gnome.org/show_bug.cgi?id=791954

**Comment by 0-wiz-0** [comment]
The problem is in the cs translation, when I disable that (remove it from `HELP_LINGUAS` in `doc/Makefile.in`), the build succeeds.

**Comment by ilovezfs** [comment]
It looks like https://github.com/itstool/itstool/commit/d3adf0264ee2b6fd28b7eff7dec33501d6e75a7c is the first bad commit.

**Comment by pyhalov** [comment]
The following workaround works fro me
```
--- itstool-2.0.5/itstool.in    2018-08-21 18:27:24.000000000 +0000
+++ itstool-2.0.5/itstool.in    2018-11-19 22:52:13.798661440 +0000
@@ -1060,9 +1060,13 @@
             if strict:
                 raise
             else:
-                sys.stderr.write('Warning: Could not merge %stranslation for msgid:\n%s\n' % (
+                try:
+                    sys.stderr.write('Warning: Could not merge %stranslation for msgid:\n%s\n' % (
                         (lang + ' ') if lang is not None else '',
                         msgstr.encode('utf-8')))
+                except UnicodeDecodeError:
+                    sys.stderr.write('Warning: Could not merge %stranslation for non-utf-8 msgid.\n' % (
+                        (lang + ' ') if lang is not None else ''))
                 self._xml_err = ''
                 return node
         def scan_node(node):
```

**Comment by belegdol** [comment]
Does not work for me unfortunately:
```if test -f "${mo}"; then mo="../${mo}"; else mo="/builddir/build/BUILD/gnumeric-1.12.42/doc/${mo}"; fi; \
(cd "cs/" && itstool -m "${mo}" ${d}/C/gnumeric.xml) && \
touch "cs/cs.stamp"
BUILDSTDERR: /bin/sh: line 4: 19276 Segmentation fault      (core dumped) itstool -m "${mo}" ${d}/C/gnumeric.xml
BUILDSTDERR: make[2]: *** [Makefile:1411: cs/cs.stamp] Error 139
BUILDSTDERR: make[2]: *** Waiting for unfinished jobs....
BUILDSTDERR: Warning: Could not merge de translation for msgid:
BUILDSTDERR: b'Permission is granted to copy, distribute and/or modify this document under the terms of the GNU Free Documentation License (GFDL), Version 1.1 or any later version published by the Free Software Foundation with no Invariant Sections, no Front-Cover Texts, and no Back-Cover Texts. You can find a copy of the GFDL at this <ulink type="help" url="ghelp:fdl">link</ulink> or in the file COPYING-DOCS distributed with this manual.'```

**Comment by belegdol** [comment]
Backtrace of the crash:
```
#0  0x00007f2d96998a75 in function_code_fastcall (globals=<optimized out>, nargs=2, args=0x7f2d86858428, co=<optimized out>)
    at /usr/src/debug/python3-3.7.1-4.fc29.x86_64/Objects/call.c:280
#1  _PyFunction_FastCallDict (func=<optimized out>, args=0x7f2d86858420, nargs=2, kwargs=<optimized out>)
    at /usr/src/debug/python3-3.7.1-4.fc29.x86_64/Objects/call.c:322
#2  0x00007f2d88c7f226 in libxml_xmlErrorFuncHandler (ctx=<optimized out>, msg=<optimized out>) at ../../python/libxml.c:1644
#3  0x00007f2d88b1babd in xmlParserPrintFileContextInternal (input=input@entry=0x560623fd77a0, 
    channel=channel@entry=0x7f2d88c7f0e0 <libxml_xmlErrorFuncHandler>, data=data@entry=0x0) at ../error.c:208
#4  0x00007f2d88b1bef7 in xmlReportError (err=err@entry=0x560623ec3648, ctxt=ctxt@entry=0x560623ec33f0, 
    str=str@entry=0x560623fd2b70 "Opening and ending tag mismatch: guilabel line 170 and para\n", 
    channel=0x7f2d88c7f0e0 <libxml_xmlErrorFuncHandler>, channel@entry=0x0, data=data@entry=0x0) at ../error.c:406
#5  0x00007f2d88b1d7d3 in __xmlRaiseError (schannel=schannel@entry=0x0, channel=0x7f2d88b1c590 <xmlParserError__internal_alias>, 
    channel@entry=0x0, data=0x560623ec33f0, data@entry=0x0, ctx=ctx@entry=0x560623ec33f0, nod=nod@entry=0x0, 
    domain=domain@entry=1, code=76, level=XML_ERR_FATAL, file=<optimized out>, line=170, str1=<optimized out>, 
    str2=<optimized out>, str3=<optimized out>, int1=170, col=490, msg=<optimized out>) at ../error.c:633
#6  0x00007f2d88b221c5 in xmlFatalErrMsgStrIntStr (ctxt=0x560623ec33f0, error=<optimized out>, msg=<optimized out>, 
    str1=<optimized out>, val=<optimized out>, str2=<optimized out>) at ../parser.c:711
#7  0x00007f2d88b2ff45 in xmlParseEndTag2 (ctxt=ctxt@entry=0x560623ec33f0, prefix=0x0, URI=0x0, line=line@entry=170, nsNr=0, 
    tlen=<optimized out>) at ../parser.c:9669
#8  0x00007f2d88b34abc in xmlParseElement__internal_alias (ctxt=ctxt@entry=0x560623ec33f0) at ../parser.c:10037
#9  0x00007f2d88b341a6 in xmlParseContent__internal_alias (ctxt=0x560623ec33f0) at ../parser.c:9846
#10 0x00007f2d88b34a59 in xmlParseElement__internal_alias (ctxt=ctxt@entry=0x560623ec33f0) at ../parser.c:10014
#11 0x00007f2d88b341a6 in xmlParseContent__internal_alias (ctxt=0x560623ec33f0) at ../parser.c:9846
#12 0x00007f2d88b34a59 in xmlParseElement__internal_alias (ctxt=ctxt@entry=0x560623ec33f0) at ../parser.c:10014
#13 0x00007f2d88b3515a in xmlParseDocument__internal_alias (ctxt=0x560623ec33f0) at ../parser.c:10711
#14 0x00007f2d88c8dd36 in libxml_xmlParseDocument (self=self@entry=<unknown at remote 0x7f2d88ff5138>, 
    args=args@entry=<unknown at remote 0x7f2d86859390>) at ../../python/libxml2-py.c:4958
#15 0x00007f2d969dff17 in _PyMethodDef_RawFastCallKeywords (method=0x7f2d88cb67e0 <libxmlMethods+9792>, 
    self=<unknown at remote 0x7f2d88ff5138>, args=0x7f2d885c7530, nargs=<optimized out>, kwnames=<optimized out>)
    at /usr/src/debug/python3-3.7.1-4.fc29.x86_64/Objects/call.c:694
#16 0x00007f2d969e01b0 in _PyCFunction_FastCallKeywords (func=<unknown at remote 0x7f2d88ffb708>, args=<optimized out>, 
    nargs=<optimized out>, kwnames=<optimized out>) at /usr/src/debug/python3-3.7.1-4.fc29.x86_64/Objects/call.c:730
#17 0x00007f2d96a57acc in call_function (kwnames=0x0, oparg=<optimized out>, pp_stack=<synthetic pointer>)
    at /usr/src/debug/python3-3.7.1-4.fc29.x86_64/Python/ceval.c:4554
#18 _PyEval_EvalFrameDefault (f=<optimized out>, throwflag=<optimized out>)
    at /usr/src/debug/python3-3.7.1-4.fc29.x86_64/Python/ceval.c:3093
#19 0x00007f2d969df78a in function_code_fastcall (globals=<optimized out>, nargs=1, args=<optimized out>, co=<optimized out>)
    at /usr/src/debug/python3-3.7.1-4.fc29.x86_64/Objects/call.c:408
#20 _PyFunction_FastCallKeywords (func=<optimized out>, stack=0x560623c89528, nargs=1, kwnames=<optimized out>)
    at /usr/src/debug/python3-3.7.1-4.fc29.x86_64/Objects/call.c:408
#21 0x00007f2d96a521d1 in call_function (kwnames=0x0, oparg=<optimized out>, pp_stack=<synthetic pointer>)
    at /usr/src/debug/python3-3.7.1-4.fc29.x86_64/Python/ceval.c:4602
#22 _PyEval_EvalFrameDefault (f=<optimized out>, throwflag=<optimized out>)
    at /usr/src/debug/python3-3.7.1-4.fc29.x86_64/Python/ceval.c:3110
#23 0x00007f2d969978e6 in _PyEval_EvalCodeWithName (_co=<optimized out>, globals=<optimized out>, locals=<optimized out>, 
    args=<optimized out>, argcount=<optimized out>, kwnames=0x7f2d8933f8e0, kwargs=0x560623d7c2f0, kwcount=<optimized out>, 
    kwstep=1, defs=0x7f2d89353d60, defcount=2, kwdefs=0x0, closure=0x0, name=<unknown at remote 0x7f2d88fa7070>, 
    qualname=<unknown at remote 0x7f2d89346e88>) at /usr/src/debug/python3-3.7.1-4.fc29.x86_64/Python/ceval.c:3930
#24 0x00007f2d969df931 in _PyFunction_FastCallKeywords (func=<optimized out>, stack=0x560623d7c2d8, nargs=3, 
    kwnames=<optimized out>) at /usr/src/debug/python3-3.7.1-4.fc29.x86_64/Objects/call.c:433
#25 0x00007f2d96a53256 in call_function (kwnames=<unknown at remote 0x7f2d8933f8c8>, oparg=<optimized out>, 
    pp_stack=<synthetic pointer>) at /usr/src/debug/python3-3.7.1-4.fc29.x86_64/Python/ceval.c:4602
#26 _PyEval_EvalFrameDefault (f=<optimized out>, throwflag=<optimized out>)
    at /usr/src/debug/python3-3.7.1-4.fc29.x86_64/Python/ceval.c:3139
#27 0x00007f2d969978e6 in _PyEval_EvalCodeWithName (_co=<optimized out>, globals=<optimized out>, locals=<optimized out>, 
    args=<optimized out>, argcount=<optimized out>, kwnames=0x7f2d89347060, kwargs=0x560623e12588, kwcount=<optimized out>, 
    kwstep=1, defs=0x7f2d89348de0, defcount=2, kwdefs=0x0, closure=0x0, name=<unknown at remote 0x7f2d88fa38a0>, 
    qualname=<unknown at remote 0x7f2d893456c0>) at /usr/src/debug/python3-3.7.1-4.fc29.x86_64/Python/ceval.c:3930
#28 0x00007f2d969df931 in _PyFunction_FastCallKeywords (func=<optimized out>, stack=0x560623e12570, nargs=3, 
    kwnames=<optimized out>) at /usr/src/debug/python3-3.7.1-4.fc29.x86_64/Objects/call.c:433
#29 0x00007f2d96a53256 in call_function (kwnames=<unknown at remote 0x7f2d89347048>, oparg=<optimized out>, 
    pp_stack=<synthetic pointer>) at /usr/src/debug/python3-3.7.1-4.fc29.x86_64/Python/ceval.c:4602
#30 _PyEval_EvalFrameDefault (f=<optimized out>, throwflag=<optimized out>)
    at /usr/src/debug/python3-3.7.1-4.fc29.x86_64/Python/ceval.c:3139
#31 0x00007f2d969978e6 in _PyEval_EvalCodeWithName (_co=<optimized out>, globals=<optimized out>, locals=<optimized out>, 
    args=<optimized out>, argcount=<optimized out>, kwnames=0x7f2d89347060, kwargs=0x560623feea18, kwcount=<optimized out>, 
    kwstep=1, defs=0x7f2d89348de0, defcount=2, kwdefs=0x0, closure=0x0, name=<unknown at remote 0x7f2d88fa38a0>, 
    qualname=<unknown at remote 0x7f2d893456c0>) at /usr/src/debug/python3-3.7.1-4.fc29.x86_64/Python/ceval.c:3930
#32 0x00007f2d969df931 in _PyFunction_FastCallKeywords (func=<optimized out>, stack=0x560623feea00, nargs=3, 
    kwnames=<optimized out>) at /usr/src/debug/python3-3.7.1-4.fc29.x86_64/Objects/call.c:433
#33 0x00007f2d96a53256 in call_function (kwnames=<unknown at remote 0x7f2d89347048>, oparg=<optimized out>, 
    pp_stack=<synthetic pointer>) at /usr/src/debug/python3-3.7.1-4.fc29.x86_64/Python/ceval.c:4602
#34 _PyEval_EvalFrameDefault (f=<optimized out>, throwflag=<optimized out>)
    at /usr/src/debug/python3-3.7.1-4.fc29.x86_64/Python/ceval.c:3139
#35 0x00007f2d969978e6 in _PyEval_EvalCodeWithName (_co=<optimized out>, globals=<optimized out>, locals=<optimized out>, 
    args=<optimized out>, argcount=<optimized out>, kwnames=0x7f2d89347060, kwargs=0x560623fba2b8, kwcount=<optimized out>, 
    kwstep=1, defs=0x7f2d89348de0, defcount=2, kwdefs=0x0, closure=0x0, name=<unknown at remote 0x7f2d88fa38a0>, 
    qualname=<unknown at remote 0x7f2d893456c0>) at /usr/src/debug/python3-3.7.1-4.fc29.x86_64/Python/ceval.c:3930
#36 0x00007f2d969df931 in _PyFunction_FastCallKeywords (func=<optimized out>, stack=0x560623fba2a0, nargs=3, 
    kwnames=<optimized out>) at /usr/src/debug/python3-3.7.1-4.fc29.x86_64/Objects/call.c:433
#37 0x00007f2d96a53256 in call_function (kwnames=<unknown at remote 0x7f2d89347048>, oparg=<optimized out>, 
    pp_stack=<synthetic pointer>) at /usr/src/debug/python3-3.7.1-4.fc29.x86_64/Python/ceval.c:4602
#38 _PyEval_EvalFrameDefault (f=<optimized out>, throwflag=<optimized out>)
    at /usr/src/debug/python3-3.7.1-4.fc29.x86_64/Python/ceval.c:3139
#39 0x00007f2d969978e6 in _PyEval_EvalCodeWithName (_co=<optimized out>, globals=<optimized out>, locals=<optimized out>, 
    args=<optimized out>, argcount=<optimized out>, kwnames=0x7f2d89347060, kwargs=0x560623f12498, kwcount=<optimized out>, 
    kwstep=1, defs=0x7f2d89348de0, defcount=2, kwdefs=0x0, closure=0x0, name=<unknown at remote 0x7f2d88fa38a0>, 
    qualname=<unknown at remote 0x7f2d893456c0>) at /usr/src/debug/python3-3.7.1-4.fc29.x86_64/Python/ceval.c:3930
#40 0x00007f2d969df931 in _PyFunction_FastCallKeywords (func=<optimized out>, stack=0x560623f12480, nargs=3, 
    kwnames=<optimized out>) at /usr/src/debug/python3-3.7.1-4.fc29.x86_64/Objects/call.c:433
#41 0x00007f2d96a53256 in call_function (kwnames=<unknown at remote 0x7f2d89347048>, oparg=<optimized out>, 
    pp_stack=<synthetic pointer>) at /usr/src/debug/python3-3.7.1-4.fc29.x86_64/Python/ceval.c:4602
#42 _PyEval_EvalFrameDefault (f=<optimized out>, throwflag=<optimized out>)
    at /usr/src/debug/python3-3.7.1-4.fc29.x86_64/Python/ceval.c:3139
#43 0x00007f2d969978e6 in _PyEval_EvalCodeWithName (_co=<optimized out>, globals=<optimized out>, locals=<optimized out>, 
    args=<optimized out>, argcount=<optimized out>, kwnames=0x7f2d89347060, kwargs=0x5606238bf248, kwcount=<optimized out>, 
    kwstep=1, defs=0x7f2d89348de0, defcount=2, kwdefs=0x0, closure=0x0, name=<unknown at remote 0x7f2d88fa38a0>, 
    qualname=<unknown at remote 0x7f2d893456c0>) at /usr/src/debug/python3-3.7.1-4.fc29.x86_64/Python/ceval.c:3930
#44 0x00007f2d969df931 in _PyFunction_FastCallKeywords (func=<optimized out>, stack=0x5606238bf230, nargs=3, 
    kwnames=<optimized out>) at /usr/src/debug/python3-3.7.1-4.fc29.x86_64/Objects/call.c:433
#45 0x00007f2d96a53256 in call_function (kwnames=<unknown at remote 0x7f2d89347048>, oparg=<optimized out>, 
    pp_stack=<synthetic pointer>) at /usr/src/debug/python3-3.7.1-4.fc29.x86_64/Python/ceval.c:4602
#46 _PyEval_EvalFrameDefault (f=<optimized out>, throwflag=<optimized out>)
    at /usr/src/debug/python3-3.7.1-4.fc29.x86_64/Python/ceval.c:3139
#47 0x00007f2d969978e6 in _PyEval_EvalCodeWithName (_co=<optimized out>, globals=<optimized out>, locals=<optimized out>, 
    args=<optimized out>, argcount=<optimized out>, kwnames=0x7f2d8934ba70, kwargs=0x7f2d894b2b80, kwcount=<optimized out>, 
    kwstep=1, defs=0x7f2d89348de0, defcount=2, kwdefs=0x0, closure=0x0, name=<unknown at remote 0x7f2d88fa38a0>, 
    qualname=<unknown at remote 0x7f2d893456c0>) at /usr/src/debug/python3-3.7.1-4.fc29.x86_64/Python/ceval.c:3930
#48 0x00007f2d969df931 in _PyFunction_FastCallKeywords (func=<optimized out>, stack=0x7f2d894b2b68, nargs=3, 
    kwnames=<optimized out>) at /usr/src/debug/python3-3.7.1-4.fc29.x86_64/Objects/call.c:433
#49 0x00007f2d96a53256 in call_function (kwnames=<unknown at remote 0x7f2d8934ba58>, oparg=<optimized out>, 
    pp_stack=<synthetic pointer>) at /usr/src/debug/python3-3.7.1-4.fc29.x86_64/Python/ceval.c:4602
#50 _PyEval_EvalFrameDefault (f=<optimized out>, throwflag=<optimized out>)
    at /usr/src/debug/python3-3.7.1-4.fc29.x86_64/Python/ceval.c:3139
#51 0x00007f2d969978e6 in _PyEval_EvalCodeWithName (_co=<optimized out>, globals=<optimized out>, locals=<optimized out>, 
    args=<optimized out>, argcount=<optimized out>, kwnames=0x0, kwargs=0x0, kwcount=<optimized out>, kwstep=2, defs=0x0, 
    defcount=0, kwdefs=0x0, closure=0x0, name=0x0, qualname=0x0) at /usr/src/debug/python3-3.7.1-4.fc29.x86_64/Python/ceval.c:3930
#52 0x00007f2d96998983 in PyEval_EvalCodeEx (_co=<optimized out>, globals=<optimized out>, locals=<optimized out>, 
    args=<optimized out>, argcount=<optimized out>, kws=<optimized out>, kwcount=0, defs=0x0, defcount=0, kwdefs=0x0, closure=0x0)
    at /usr/src/debug/python3-3.7.1-4.fc29.x86_64/Python/ceval.c:3959
#53 0x00007f2d969989ab in PyEval_EvalCode (co=co@entry=<unknown at remote 0x7f2d88f9b030>, 
    globals=globals@entry=<unknown at remote 0x7f2d89418288>, locals=locals@entry=<unknown at remote 0x7f2d89418288>)
    at /usr/src/debug/python3-3.7.1-4.fc29.x86_64/Python/ceval.c:524
#54 0x00007f2d96ac720e in run_mod (mod=mod@entry=0x56062109f2d8, filename=filename@entry=<unknown at remote 0x7f2d8935c540>, 
    globals=globals@entry=<unknown at remote 0x7f2d89418288>, locals=locals@entry=<unknown at remote 0x7f2d89418288>, 
    flags=flags@entry=0x7ffee1266af0, arena=arena@entry=0x7f2d895120a8)
    at /usr/src/debug/python3-3.7.1-4.fc29.x86_64/Python/pythonrun.c:1035
#55 0x00007f2d96ac9086 in PyRun_FileExFlags (fp=0x560620fc7c60, filename_str=<optimized out>, start=<optimized out>, globals=<unknown at remote 0x7f2d89418288>, locals=<unknown at remote 0x7f2d89418288>, closeit=1, flags=0x7ffee1266af0) at /usr/src/debug/python3-3.7.1-4.fc29.x86_64/Python/pythonrun.c:988
#56 0x00007f2d96aca648 in PyRun_SimpleFileExFlags (fp=0x560620fc7c60, filename=<optimized out>, closeit=1, flags=0x7ffee1266af0) at /usr/src/debug/python3-3.7.1-4.fc29.x86_64/Python/pythonrun.c:429
#57 0x00007f2d96acc801 in pymain_run_file (p_cf=0x7ffee1266af0, filename=0x560620f7f540 L"/usr/bin/itstool", fp=0x560620fc7c60) at /usr/src/debug/python3-3.7.1-4.fc29.x86_64/Modules/main.c:427
#58 pymain_run_filename (cf=0x7ffee1266af0, pymain=0x7ffee1266c00) at /usr/src/debug/python3-3.7.1-4.fc29.x86_64/Modules/main.c:1537
#59 pymain_run_python (pymain=0x7ffee1266c00) at /usr/src/debug/python3-3.7.1-4.fc29.x86_64/Modules/main.c:2626
#60 pymain_main (pymain=<optimized out>, pymain=<optimized out>) at /usr/src/debug/python3-3.7.1-4.fc29.x86_64/Modules/main.c:2787
#61 0x00007f2d96accbdc in _Py_UnixMain (argc=<optimized out>, argv=<optimized out>) at /usr/src/debug/python3-3.7.1-4.fc29.x86_64/Modules/main.c:2822
#62 0x00007f2d9653a413 in __libc_start_main (main=0x560620206050<error reading variable>, argc=6, argv=0x7ffee1266d58, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7ffee1266d48) at ../csu/libc-start.c:308
#63 0x000056062020608e in _start ()
```

**Comment by besser82** [comment]
@belegdol I just fixed this in Fedora 29 and 30.

The issue was in `libxml2` [1] and there was a patch for it here [2].


[1]  https://bugzilla.gnome.org/show_bug.cgi?id=789714
[2]  https://bugzilla.opensuse.org/show_bug.cgi?id=1065270

**Comment by mwelinder** [comment]
This is still a problem for Gnumeric with itstool-2.0.6.

Some runs with valgrind show problems, others do not.  This is with the same input, command line, etc. Here is an example. (With a slightly modified itstool with an extra print statement on line 1002.)
```
# PYTHONMALLOC=malloc valgrind ~/itstool -m "../cs/cs.mo" ../C/gnumeric.xml
[...]
=380953== Conditional jump or move depends on uninitialised value(s)
==380953==    at 0x58A64F: PyUnicode_Decode (in /usr/bin/python3.8)
==380953==    by 0x58A9A4: PyUnicode_FromEncodedObject (in /usr/bin/python3.8)
==380953==    by 0x575A9A: ??? (in /usr/bin/python3.8)
==380953==    by 0x5F3332: _PyObject_MakeTpCall (in /usr/bin/python3.8)
==380953==    by 0x56F1C9: _PyEval_EvalFrameDefault (in /usr/bin/python3.8)
==380953==    by 0x5F5E55: _PyFunction_Vectorcall (in /usr/bin/python3.8)
==380953==    by 0x59B763: ??? (in /usr/bin/python3.8)
==380953==    by 0x5F33AE: _PyObject_MakeTpCall (in /usr/bin/python3.8)
==380953==    by 0x56F1C9: _PyEval_EvalFrameDefault (in /usr/bin/python3.8)
==380953==    by 0x568229: _PyEval_EvalCodeWithName (in /usr/bin/python3.8)
==380953==    by 0x5F6032: _PyFunction_Vectorcall (in /usr/bin/python3.8)
==380953==    by 0x56EF96: _PyEval_EvalFrameDefault (in /usr/bin/python3.8)
==380953== 
Traceback (most recent call last):
  File "/home/welinder/itstool", line 1615, in <module>
    doc.merge_translations(translations, opts.lang, strict=opts.strict)
  File "/home/welinder/itstool", line 1003, in merge_translations
    lcnode.setProp(attr, origlang)
  File "/usr/lib/python3/dist-packages/libxml2.py", line 3588, in setProp
    if ret is None:raise treeError('xmlSetProp() failed')
libxml2.treeError: xmlSetProp() failed
```

The now-you-see-it-and-now-you-don't part suggests memory corruption to me.  I have seen core dumps without valgrind.  This is with the above command line minus the PYTHONMALLOC setting.

The translation item being processed at the time of the crash varies.

Here's a stack trace under gdb.  I'm not sure how useful it is.
```
Program received signal SIGSEGV, Segmentation fault.
0x00007ffff69ecf47 in ?? () from /usr/lib/python3/dist-packages/libxml2mod.cpython-38-x86_64-linux-gnu.so
(gdb) where
#0  0x00007ffff69ecf47 in ?? () from /usr/lib/python3/dist-packages/libxml2mod.cpython-38-x86_64-linux-gnu.so
#1  0x00000000005f305a in PyCFunction_Call ()
#2  0x00000000005f3446 in _PyObject_MakeTpCall ()
#3  0x000000000056f600 in _PyEval_EvalFrameDefault ()
#4  0x00000000005f5e56 in _PyFunction_Vectorcall ()
#5  0x0000000000569f5e in _PyEval_EvalFrameDefault ()
#6  0x0000000000502c4f in ?? ()
#7  0x00000000005becc7 in PyObject_GetAttr ()
#8  0x0000000000569e8d in _PyEval_EvalFrameDefault ()
#9  0x000000000056822a in _PyEval_EvalCodeWithName ()
#10 0x000000000050a3b0 in ?? ()
#11 0x000000000056b115 in _PyEval_EvalFrameDefault ()
#12 0x000000000056822a in _PyEval_EvalCodeWithName ()
#13 0x000000000068c1e7 in PyEval_EvalCode ()
#14 0x000000000067d5a1 in ?? ()
#15 0x000000000067d61f in ?? ()
#16 0x000000000067d6db in PyRun_FileExFlags ()
#17 0x000000000067da6e in PyRun_SimpleFileExFlags ()
#18 0x00000000006b6132 in Py_RunMain ()
#19 0x00000000006b64bd in Py_BytesMain ()
#20 0x00007ffff7dda0b3 in __libc_start_main (main=0x4eec80 <main>, argc=5, argv=0x7fffffffdf08, init=<optimized out>, fini=<optimized out>, 
    rtld_fini=<optimized out>, stack_end=0x7fffffffdef8) at ../csu/libc-start.c:308
#21 0x00000000005f927e in _start ()
```
